# Generated by Django 2.2.7 on 2019-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='smp_head_contact_number',
            field=models.CharField(default='8296889713', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sig',
            name='smp_head_name',
            field=models.CharField(default='Gautam', max_length=50),
            preserve_default=False,
        ),
    ]
