# Generated by Django 2.2.9 on 2020-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0004_auto_20200323_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='poster_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='report_link',
        ),
        migrations.AddField(
            model_name='projects',
            name='conclusion',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='uploads/projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='duration_in_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='future_work',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='introduction',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='mentors',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='method',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='obstacles',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='references',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='results',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
