# Generated by Django 2.2.9 on 2020-07-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0005_auto_20200714_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='uploads/projects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acm.Projects')),
            ],
        ),
    ]
