# Generated by Django 2.2.9 on 2020-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0006_projectpictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
        migrations.AddField(
            model_name='projectpictures',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='meet_link',
            field=models.CharField(default='https://www.google.com/', max_length=500),
            preserve_default=False,
        ),
    ]
