# Generated by Django 2.2.9 on 2020-07-23 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0007_auto_20200723_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpictures',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/projects', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='uploads/projects', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
