# Generated by Django 2.2.9 on 2020-07-24 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0008_auto_20200723_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='projectpictures',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='duration_in_months',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='future_work',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='meet_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='mentors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='method',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='obstacles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='results',
            field=models.TextField(blank=True),
        ),
    ]
