# Generated by Django 2.0 on 2020-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0010_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
