# Generated by Django 2.2.9 on 2020-08-11 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0011_proposals_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sigs', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='sig',
            name='mission_statement',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sig',
            name='vision_statement',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
