# Generated by Django 2.0 on 2021-08-05 06:12
import django
from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('acm', '0014_projects_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='Events',
            name='image',
            field=models.ImageField(upload_to='uploads/events', blank=True, null=True, validators=[
                FileExtensionValidator(['jpg', 'jpeg', 'png', ])]),
        ),
        migrations.AlterField(
            model_name='Events',
            name='sig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acm.SIG', null=True)
        )
    ]
