# Generated by Django 2.0 on 2021-08-07 06:57
from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0015_add_image_to_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Special_people',
            old_name='fb_link',
            new_name='email_link'
        ),
        migrations.RemoveField(
            model_name='Proposals',
            name='members'
        ),
        migrations.AddField(
            model_name='Proposals',
            name='learning_outcomes',
            field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name='Proposals',
            name='results',
            field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name='Proposals',
            name='image',
            field=models.ImageField(upload_to='uploads/proposals', blank=True, null=True, validators=[
                FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='ProposalTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField(blank=True)),
                ('tasks', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('proposal_id', models.ForeignKey(on_delete=models.deletion.CASCADE, to='acm.Proposals'))
            ]
        )
    ]
