# Generated by Django 2.2.7 on 2019-12-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mentors', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=2000)),
                ('platform_of_tutoring', models.CharField(max_length=1000)),
                ('sig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acm.SIG')),
            ],
        ),
        migrations.CreateModel(
            name='SMP_des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=200)),
                ('sub_id', models.IntegerField()),
                ('sub_des', models.CharField(max_length=1000)),
                ('smp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMP.SMP')),
            ],
        ),
    ]
