# Generated by Django 2.2.7 on 2019-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smp_des',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='smp',
            name='head_contact_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smp',
            name='head_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
