# Generated by Django 2.0 on 2020-01-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0003_auto_20191209_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smp',
            name='sig_id',
        ),
        migrations.RemoveField(
            model_name='smp_des',
            name='smp_id',
        ),
        migrations.DeleteModel(
            name='SMP',
        ),
        migrations.DeleteModel(
            name='SMP_des',
        ),
    ]
