# Generated by Django 2.0 on 2020-01-04 18:40

import SMP.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SMP', '0004_auto_20200104_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('mentors', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=2000)),
                ('platform_of_tutoring', models.CharField(max_length=1000)),
                ('exercises', djongo.models.fields.ArrayModelField(default=[], model_container=SMP.models.Description)),
                ('prerequisites', djongo.models.fields.ArrayModelField(default=[], model_container=SMP.models.Description)),
                ('course_content', djongo.models.fields.ArrayModelField(default=[], model_container=SMP.models.Description)),
                ('weekly_plan', djongo.models.fields.ArrayModelField(default=[], model_container=SMP.models.WeeklyPlan)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_description', djongo.models.fields.ArrayModelField(default=[], model_container=SMP.models.Description)),
            ],
        ),
    ]
